-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.usuarios
(
    usuario_id serial NOT NULL,
    usuario_username character varying(50) NOT NULL,
    usuario_contrasenia character varying(255) NOT NULL,
    usuario_correo character varying(50),
    usuario_apellido character varying(50) NOT NULL,
    usuario_nombre character varying(50) NOT NULL,
    usuario_activo boolean NOT NULL,
    usuario_debe_cambiar_contrasenia boolean NOT NULL DEFAULT false,
    usuario_fecha_reset timestamp without time zone,
    rol_id integer NOT NULL,
    PRIMARY KEY (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    rol_id serial NOT NULL,
    rol_nombre character varying(100) NOT NULL,
    PRIMARY KEY (rol_id)
);

CREATE TABLE IF NOT EXISTS public.permisos
(
    permiso_id serial NOT NULL,
    permiso_nombre character varying(25) NOT NULL,
    PRIMARY KEY (permiso_id)
);

CREATE TABLE IF NOT EXISTS public.roles_permisos
(
    usuario_debe_cambiar_contrasenia boolean NOT NULL DEFAULT false,
    usuario_fecha_reset timestamp without time zone,
    rol_id integer NOT NULL,
    permiso_id integer NOT NULL,
    PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS public.docentes
(
    usuario_id integer NOT NULL,
    docente_dni bigint NOT NULL,
    docente_cuil bigint NOT NULL,
    docente_fecha_nac date NOT NULL,
    docente_email_institucional character varying(60),
    docente_fecha_ingreso date NOT NULL,
    docente_domicilio character varying(100),
    docente_antig_previa integer,
    docente_estado character varying(15) NOT NULL DEFAULT 'Inactivo',
    PRIMARY KEY (usuario_id),
    UNIQUE (docente_dni),
    UNIQUE (docente_cuil),
    UNIQUE (docente_email_institucional)
);

CREATE TABLE IF NOT EXISTS public.admin_globales
(
    usuario_id integer NOT NULL,
    cargo_ag_nombre character varying(40) NOT NULL,
    PRIMARY KEY (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.admin_de_unidad
(
    usuario_id integer NOT NULL,
    cargo_ad_nombre character varying(40) NOT NULL,
    unidad_id integer NOT NULL,
    PRIMARY KEY (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.auditores
(
    usuario_id integer NOT NULL,
    cargo_aud_nombre character varying(40) NOT NULL,
    PRIMARY KEY (usuario_id)
);

CREATE TABLE IF NOT EXISTS public.telefonos_docentes
(
    docente_usuario_id integer NOT NULL,
    docente_telefono character varying(20) NOT NULL,
    PRIMARY KEY (docente_usuario_id, docente_telefono)
);

CREATE TABLE IF NOT EXISTS public.designaciones
(
    designacion_id serial NOT NULL,
    designacion_numero_resolucion integer NOT NULL,
    designacion_fecha_inicio date NOT NULL,
    designacion_fecha_fin date,
    designacion_estado_actual character varying(40) NOT NULL DEFAULT 'Activo',
    usuario_id integer NOT NULL,
    PRIMARY KEY (designacion_id)
);

CREATE TABLE IF NOT EXISTS public.cargos
(
    cargo_id serial NOT NULL,
    cargo_codigo bigint NOT NULL,
    cargo_horas_ocupadas integer NOT NULL,
    cargo_fecha_creacion date NOT NULL,
    cargo_predecesor_id integer,
    cargo_origen_division integer,
    origen_id integer NOT NULL,
    caracter_id integer NOT NULL,
    categoria_id integer NOT NULL,
    dedicacion_id integer NOT NULL,
    designacion_id integer NOT NULL,
    unidad_id integer NOT NULL,
    cargo_estado character varying(20) NOT NULL DEFAULT 'Libre',
    PRIMARY KEY (cargo_id)
);

CREATE TABLE IF NOT EXISTS public.funciones
(
    funcion_id serial NOT NULL,
    funcion_nombre character varying(100) NOT NULL,
    funcion_horas integer NOT NULL,
    cargo_id integer NOT NULL,
    materia_id integer NOT NULL,
    PRIMARY KEY (funcion_id)
);

CREATE TABLE IF NOT EXISTS public.materias
(
    materia_id serial NOT NULL,
    materia_nombre character varying(50) NOT NULL,
    materia_horas integer NOT NULL,
    materia_anio integer NOT NULL,
    materia_despliegue character varying(50) NOT NULL,
    unidad_id integer NOT NULL,
    PRIMARY KEY (materia_id)
);

CREATE TABLE IF NOT EXISTS public.subrogancias
(
    subrogancia_id serial NOT NULL,
    subrogancia_nro_resolucion character varying(20),
    subrogancia_fecha_inicio date NOT NULL,
    subrogancia_fecha_fin date,
    cargo_id integer NOT NULL,
    PRIMARY KEY (subrogancia_id)
);

CREATE TABLE IF NOT EXISTS public.cambios
(
    cambio_id serial NOT NULL,
    cambio_tabla_afectada character varying(50) NOT NULL,
    cambio_campo_afectado character varying(50) NOT NULL,
    cambio_valor_anterior character varying(100) NOT NULL,
    cambio_valor_nuevo character varying(100) NOT NULL,
    cambio_fecha_hora date NOT NULL,
    usuario_id integer NOT NULL,
    PRIMARY KEY (cambio_id)
);

CREATE TABLE IF NOT EXISTS public.licencias
(
    licencia_id serial NOT NULL,
    licencia_nro_resolucion character varying(20),
    licencia_fecha_inicio date NOT NULL,
    licencia_fecha_fin date,
    licencia_fecha_fin_estim date,
    motivo_id integer NOT NULL,
    licencia_cantidad_dias integer NOT NULL,
    designacion_id integer NOT NULL,
    PRIMARY KEY (licencia_id)
);

CREATE TABLE IF NOT EXISTS public.origen
(
    origen_id serial NOT NULL,
    origen_nombre character varying(50) NOT NULL,
    PRIMARY KEY (origen_id)
);

CREATE TABLE IF NOT EXISTS public.caracteres
(
    caracter_id serial NOT NULL,
    caracter_nombre character varying(100) NOT NULL,
    PRIMARY KEY (caracter_id)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    categoria_id serial NOT NULL,
    categoria_nombre character varying(40) NOT NULL,
    PRIMARY KEY (categoria_id)
);

CREATE TABLE IF NOT EXISTS public.dedicaciones
(
    dedicacion_id serial NOT NULL,
    dedicacion_nombre character varying(50) NOT NULL,
    dedicacion_horas integer,
    PRIMARY KEY (dedicacion_id)
);

CREATE TABLE IF NOT EXISTS public.unidades
(
    unidad_id serial NOT NULL,
    unidad_nombre character varying(100) NOT NULL,
    tipo_unidad_id integer NOT NULL,
    PRIMARY KEY (unidad_id)
);

CREATE TABLE IF NOT EXISTS public.motivos_licencias
(
    motivo_l_id integer NOT NULL,
    motivo_l_nombre character varying(100) NOT NULL,
    motivo_l_dias_corresp integer NOT NULL,
    PRIMARY KEY (motivo_l_id)
);

CREATE TABLE IF NOT EXISTS public.renuncias
(
    renuncia_id serial NOT NULL,
    renuncia_nro_resolucion character varying(20) NOT NULL,
    renuncia_fecha date NOT NULL,
    renuncia_fecha_efectiva date NOT NULL,
    motivo_id integer NOT NULL,
    designacion_id integer NOT NULL,
    PRIMARY KEY (renuncia_id)
);

CREATE TABLE IF NOT EXISTS public.motivos_renuncias
(
    motivo_r_id integer NOT NULL,
    motivo_r_nombre character varying(50) NOT NULL,
    PRIMARY KEY (motivo_r_id)
);

CREATE TABLE IF NOT EXISTS public.tipo_de_unidad
(
    tipo_unidad_id serial NOT NULL,
    tipo_unidad_nombre character varying(20),
    PRIMARY KEY (tipo_unidad_id)
);

CREATE TABLE IF NOT EXISTS public.catedras
(
    catedra_id serial NOT NULL,
    catedra_nombre character varying(50) NOT NULL,
    catedra_tipologia integer NOT NULL,
    catedra_estado character varying(15) NOT NULL,
    catedra_director_id integer NOT NULL,
    materia_id integer NOT NULL,
    PRIMARY KEY (catedra_id),
    UNIQUE (catedra_director_id)
);

CREATE TABLE IF NOT EXISTS public.archivos
(
    archivo_id serial NOT NULL,
    archivo_nombre_original character varying(255) NOT NULL,
    archivo_nombre_encriptado character varying(255) NOT NULL,
    archivo_tipo_tramite character varying(50) NOT NULL,
    archivo_tramite_id integer NOT NULL,
    archivo_fecha_subida timestamp without time zone NOT NULL,
    archivo_tamano bigint NOT NULL,
    archivo_tipo_contenido character varying(100) NOT NULL,
    PRIMARY KEY (archivo_id),
    UNIQUE (archivo_nombre_encriptado)
);

ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT fk_usuarios_roles FOREIGN KEY (rol_id)
    REFERENCES public.roles (rol_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_permisos
    ADD CONSTRAINT pk_rp_roles FOREIGN KEY (rol_id)
    REFERENCES public.roles (rol_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_permisos
    ADD CONSTRAINT pk_rp_permisos FOREIGN KEY (permiso_id)
    REFERENCES public.permisos (permiso_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.docentes
    ADD CONSTRAINT fk_docentes_usuarios FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.admin_globales
    ADD CONSTRAINT pk_admin_global_usuario FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.admin_de_unidad
    ADD CONSTRAINT fk_admin_unidad_usuario FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.admin_de_unidad
    ADD CONSTRAINT fk_admin_unidad_unidad FOREIGN KEY (unidad_id)
    REFERENCES public.unidades (unidad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.auditores
    ADD CONSTRAINT fk_auditores_usuarios FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.telefonos_docentes
    ADD CONSTRAINT pk_telefono_docente FOREIGN KEY (docente_usuario_id)
    REFERENCES public.docentes (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.designaciones
    ADD CONSTRAINT fk_designacion_usuario FOREIGN KEY (usuario_id)
    REFERENCES public.docentes (usuario_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_designaciones FOREIGN KEY (designacion_id)
    REFERENCES public.designaciones (designacion_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_origen FOREIGN KEY (origen_id)
    REFERENCES public.origen (origen_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_caracteres FOREIGN KEY (caracter_id)
    REFERENCES public.caracteres (caracter_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_categorias FOREIGN KEY (categoria_id)
    REFERENCES public.categorias (categoria_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_dedicaciones FOREIGN KEY (dedicacion_id)
    REFERENCES public.dedicaciones (dedicacion_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargos_unidades FOREIGN KEY (unidad_id)
    REFERENCES public.unidades (unidad_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargo_predecesor FOREIGN KEY (cargo_predecesor_id)
    REFERENCES public.cargos (cargo_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cargos
    ADD CONSTRAINT fk_cargo_origen FOREIGN KEY (cargo_origen_division)
    REFERENCES public.cargos (cargo_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.funciones
    ADD FOREIGN KEY (cargo_id)
    REFERENCES public.cargos (cargo_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.funciones
    ADD FOREIGN KEY (materia_id)
    REFERENCES public.materias (materia_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.materias
    ADD FOREIGN KEY (unidad_id)
    REFERENCES public.unidades (unidad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subrogancias
    ADD CONSTRAINT fk_subrogancias_cargos FOREIGN KEY (cargo_id)
    REFERENCES public.cargos (cargo_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.cambios
    ADD CONSTRAINT fk_cambios_usuarios FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.licencias
    ADD CONSTRAINT fk_licencias_designaciones FOREIGN KEY (designacion_id)
    REFERENCES public.designaciones (designacion_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.licencias
    ADD CONSTRAINT fk_licencias_motivos_l FOREIGN KEY (motivo_id)
    REFERENCES public.motivos_licencias (motivo_l_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.unidades
    ADD CONSTRAINT fk_unidades_tipo_unidades FOREIGN KEY (tipo_unidad_id)
    REFERENCES public.tipo_de_unidad (tipo_unidad_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.renuncias
    ADD CONSTRAINT fk_renuncia_designacion FOREIGN KEY (designacion_id)
    REFERENCES public.designaciones (designacion_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.renuncias
    ADD CONSTRAINT fk_renuncias_motivos_r FOREIGN KEY (motivo_id)
    REFERENCES public.motivos_renuncias (motivo_r_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.catedras
    ADD CONSTRAINT fk_catedras_materia FOREIGN KEY (materia_id)
    REFERENCES public.materias (materia_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.catedras
    ADD CONSTRAINT fk_catedras_docente FOREIGN KEY (catedra_director_id)
    REFERENCES public.docentes (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

-- 1. Insert Tipo de Unidad
INSERT INTO public.tipo_de_unidad (tipo_unidad_nombre) VALUES
('Centro'),
('Departamento'),
('Instituto');

-- The above will likely get IDs 1, 2, 3 assuming the table is empty.
-- We will use subqueries to be safe.

-- 2. Insert Centros
INSERT INTO public.unidades (unidad_nombre, tipo_unidad_id) VALUES
('Creación. Art. Coral', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Centro')),
('Creación. Art. Orq.', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Centro')),
('Tornambé Centro de Creación', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Centro'));

-- 3. Insert Departamentos
INSERT INTO public.unidades (unidad_nombre, tipo_unidad_id) VALUES
('Artes Visuales', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Filosofía y Ciencias de la Educación', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Física, Química y Tec.', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Geografía', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Historia', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Lengua y Literatura Inglesa', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Letras', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Matemática', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Música', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento')),
('Turismo', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Departamento'));

-- 4. Insert Institutos
INSERT INTO public.unidades (unidad_nombre, tipo_unidad_id) VALUES
('Ciencias Básicas - ICB', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Geografía Aplicada', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Estudios Musicales', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Experiencia Visual', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Filosofía', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Investig. Lingüísticas y Filológicas', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Investig. Aqueológicas y Museo', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Investig. en Ciencias de la Educación', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Investig. en Educación en Ciencias Experimentales', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Investig. en Historia Regional y Argentina', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto')),
('Litertura - Ricardo Güiraldes', (SELECT tipo_unidad_id FROM public.tipo_de_unidad WHERE tipo_unidad_nombre = 'Instituto'));


-- 5. Insert Roles
INSERT INTO public.roles (rol_nombre) VALUES
('Administrador Global'),
('Administrador de Unidad'),
('Auditor'),
('Docente');

-- 6. Insert Usuarios
INSERT INTO public.usuarios (usuario_username, usuario_contrasenia, usuario_correo, usuario_apellido, usuario_nombre, usuario_activo, rol_id) VALUES
('admin', crypt('admin123', gen_salt('bf', 10)), 'admin@atlas.edu', 'Sistema', 'Administrador', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Administrador Global')),
('jperez', crypt('docente123', gen_salt('bf', 10)), 'jperez@atlas.edu', 'Perez', 'Juan', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('mgomez', crypt('admin123', gen_salt('bf', 10)), 'mgomez@atlas.edu', 'Gomez', 'Maria', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Administrador de Unidad'));

-- 7. Insert Origenes, Caracteres, Categorias, Dedicaciones
INSERT INTO public.origen (origen_nombre) VALUES
('Planta'),
('Investigación'),
('Extensión'),
('Gestión');

INSERT INTO public.caracteres (caracter_nombre) VALUES
('Efectivo'),
('Extraordinario'),
('Interino'),
('Suplente Constituido'),
('Suplente Reemplazante');

INSERT INTO public.categorias (categoria_nombre) VALUES
('Titular'),
('Jefe de Trabajos Prácticos'),
('Adjunto'),
('Asociado'),
('Auxiliar de Primera'),
('Auxiliar de Segunda');

INSERT INTO public.dedicaciones (dedicacion_nombre, dedicacion_horas) VALUES
('Exclusiva', 40),
('Semi-Exclusiva', 20),
('Simple', 10);


-- =========================================================================
-- ADDITIONAL MOCK DATA FOR COMPREHENSIVE TESTING (DOCENTES, CARGOS, UNIDADES)
-- =========================================================================

-- More Users (Docentes)
INSERT INTO public.usuarios (usuario_username, usuario_contrasenia, usuario_correo, usuario_apellido, usuario_nombre, usuario_activo, rol_id) VALUES
('agarcia', crypt('pass123', gen_salt('bf', 10)), 'agarcia@atlas.edu', 'Garcia', 'Ana', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('lmartinez', crypt('pass123', gen_salt('bf', 10)), 'lmartinez@atlas.edu', 'Martinez', 'Luis', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('crodriguez', crypt('pass123', gen_salt('bf', 10)), 'crodriguez@atlas.edu', 'Rodriguez', 'Carlos', false, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('sfernandez', crypt('pass123', gen_salt('bf', 10)), 'sfernandez@atlas.edu', 'Fernandez', 'Sofia', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente'));

-- Docentes Details
INSERT INTO public.docentes (usuario_id, docente_dni, docente_cuil, docente_fecha_nac, docente_email_institucional, docente_fecha_ingreso, docente_domicilio, docente_antig_previa, docente_estado) VALUES
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'jperez'), 30111222, 20301112224, '1985-04-12', 'jperez@atlas.edu', '2010-03-01', 'Calle Falsa 123', 0, 'Activo'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'agarcia'), 32333444, 27323334445, '1987-08-22', 'agarcia@atlas.edu', '2015-05-15', 'Av. Siempreviva 742', 2, 'Activo'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'lmartinez'), 28555666, 20285556668, '1982-11-05', 'lmartinez@atlas.edu', '2008-04-10', 'San Martin 555', 5, 'Activo'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'crodriguez'), 29444777, 20294447771, '1984-01-30', 'crodriguez@atlas.edu', '2012-08-01', 'Belgrano 1000', 1, 'Inactivo'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'sfernandez'), 35888999, 27358889993, '1991-09-18', 'sfernandez@atlas.edu', '2018-03-01', 'Sarmiento 200', 0, 'Activo');

-- Telefonos
INSERT INTO public.telefonos_docentes (docente_usuario_id, docente_telefono) VALUES
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'jperez'), '264-1111111'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'agarcia'), '264-2222222');

-- Designaciones (Activo except for Carlos Rodriguez)
INSERT INTO public.designaciones (designacion_numero_resolucion, designacion_fecha_inicio, designacion_estado_actual, usuario_id) VALUES
(1001, '2010-03-01', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'jperez')),
(1002, '2015-05-15', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'agarcia')),
(1003, '2008-04-10', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'lmartinez')),
(1004, '2012-08-01', 'Inactivo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'crodriguez')),
(1005, '2018-03-01', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'sfernandez'));

-- Materias
INSERT INTO public.materias (materia_nombre, materia_horas, materia_anio, materia_despliegue, unidad_id) VALUES
('Matematica I', 80, 1, 'Anual', (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Matemática' LIMIT 1)),
('Fisica I', 60, 1, 'Cuatrimestral', (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Física, Química y Tec.' LIMIT 1)),
('Historia del Arte', 40, 2, 'Cuatrimestral', (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Artes Visuales' LIMIT 1)),
('Coro Universitario', 120, 1, 'Anual', (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Creación. Art. Coral' LIMIT 1));

-- Cargos 
-- jperez: Titular, Exclusiva, Matematica
INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(5001, 40, '2010-03-01', 
 (SELECT origen_id FROM public.origen WHERE origen_nombre = 'Planta' LIMIT 1),
 (SELECT caracter_id FROM public.caracteres WHERE caracter_nombre = 'Efectivo' LIMIT 1),
 (SELECT categoria_id FROM public.categorias WHERE categoria_nombre = 'Titular' LIMIT 1),
 (SELECT dedicacion_id FROM public.dedicaciones WHERE dedicacion_nombre = 'Exclusiva' LIMIT 1),
 (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'jperez') LIMIT 1),
 (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Matemática' LIMIT 1)
);

-- agarcia: Adjunto, Semiexclusiva, Fisica
INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(5002, 20, '2015-05-15', 
 (SELECT origen_id FROM public.origen WHERE origen_nombre = 'Planta' LIMIT 1),
 (SELECT caracter_id FROM public.caracteres WHERE caracter_nombre = 'Interino' LIMIT 1),
 (SELECT categoria_id FROM public.categorias WHERE categoria_nombre = 'Adjunto' LIMIT 1),
 (SELECT dedicacion_id FROM public.dedicaciones WHERE dedicacion_nombre = 'Semi-Exclusiva' LIMIT 1),
 (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'agarcia') LIMIT 1),
 (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Física, Química y Tec.' LIMIT 1)
);

-- lmartinez: JTP, Simple, Historia del Arte
INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(5003, 10, '2008-04-10', 
 (SELECT origen_id FROM public.origen WHERE origen_nombre = 'Planta' LIMIT 1),
 (SELECT caracter_id FROM public.caracteres WHERE caracter_nombre = 'Efectivo' LIMIT 1),
 (SELECT categoria_id FROM public.categorias WHERE categoria_nombre = 'Jefe de Trabajos Prácticos' LIMIT 1),
 (SELECT dedicacion_id FROM public.dedicaciones WHERE dedicacion_nombre = 'Simple' LIMIT 1),
 (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'lmartinez') LIMIT 1),
 (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Artes Visuales' LIMIT 1)
);

-- sfernandez: JTP, Simple, Coro Universitario
INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(5004, 10, '2018-03-01', 
 (SELECT origen_id FROM public.origen WHERE origen_nombre = 'Investigación' LIMIT 1),
 (SELECT caracter_id FROM public.caracteres WHERE caracter_nombre = 'Suplente Constituido' LIMIT 1),
 (SELECT categoria_id FROM public.categorias WHERE categoria_nombre = 'Auxiliar de Primera' LIMIT 1),
 (SELECT dedicacion_id FROM public.dedicaciones WHERE dedicacion_nombre = 'Simple' LIMIT 1),
 (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'sfernandez') LIMIT 1),
 (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Creación. Art. Coral' LIMIT 1)
);

-- Funciones (Linking Cargos with Materias)
INSERT INTO public.funciones (funcion_nombre, funcion_horas, cargo_id, materia_id) VALUES
('Dictado de Clases', 10, 
 (SELECT cargo_id FROM public.cargos WHERE cargo_codigo = 5001 LIMIT 1),
 (SELECT materia_id FROM public.materias WHERE materia_nombre = 'Matematica I' LIMIT 1)
),
('Dictado de Clases', 8, 
 (SELECT cargo_id FROM public.cargos WHERE cargo_codigo = 5002 LIMIT 1),
 (SELECT materia_id FROM public.materias WHERE materia_nombre = 'Fisica I' LIMIT 1)
),
('Apoyo Practico', 4, 
 (SELECT cargo_id FROM public.cargos WHERE cargo_codigo = 5003 LIMIT 1),
 (SELECT materia_id FROM public.materias WHERE materia_nombre = 'Historia del Arte' LIMIT 1)
),
('Ensayo', 10, 
 (SELECT cargo_id FROM public.cargos WHERE cargo_codigo = 5004 LIMIT 1),
 (SELECT materia_id FROM public.materias WHERE materia_nombre = 'Coro Universitario' LIMIT 1)
);

-- =========================================================================
-- ADDITIONAL MOCK DATA: ONE DOCENTE FOR EVERY OTHER UNIDAD
-- =========================================================================

-- 1. Insert 20 extra users
INSERT INTO public.usuarios (usuario_username, usuario_contrasenia, usuario_correo, usuario_apellido, usuario_nombre, usuario_activo, rol_id) VALUES
('doc_orq', crypt('pass123', gen_salt('bf', 10)), 'doc_orq@atlas.edu', 'Perez', 'Diego', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_tornambe', crypt('pass123', gen_salt('bf', 10)), 'doc_tornambe@atlas.edu', 'Gomez', 'Lucia', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_filo', crypt('pass123', gen_salt('bf', 10)), 'doc_filo@atlas.edu', 'Lopez', 'Matias', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_geo', crypt('pass123', gen_salt('bf', 10)), 'doc_geo@atlas.edu', 'Diaz', 'Valentina', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_historia', crypt('pass123', gen_salt('bf', 10)), 'doc_historia@atlas.edu', 'Ruiz', 'Agustin', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_ingles', crypt('pass123', gen_salt('bf', 10)), 'doc_ingles@atlas.edu', 'Blanco', 'John', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_letras', crypt('pass123', gen_salt('bf', 10)), 'doc_letras@atlas.edu', 'Alvarez', 'Jorge', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_musica', crypt('pass123', gen_salt('bf', 10)), 'doc_musica@atlas.edu', 'Navarro', 'Camila', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_turismo', crypt('pass123', gen_salt('bf', 10)), 'doc_turismo@atlas.edu', 'Fernandez', 'Tomas', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_icb', crypt('pass123', gen_salt('bf', 10)), 'doc_icb@atlas.edu', 'Rossi', 'Giulia', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_geo_ap', crypt('pass123', gen_salt('bf', 10)), 'doc_geo_ap@atlas.edu', 'Martinez', 'Ignacio', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_est_mus', crypt('pass123', gen_salt('bf', 10)), 'doc_est_mus@atlas.edu', 'Gimenez', 'Carolina', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_exp_vis', crypt('pass123', gen_salt('bf', 10)), 'doc_exp_vis@atlas.edu', 'Ramos', 'Federico', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_inst_filo', crypt('pass123', gen_salt('bf', 10)), 'doc_inst_filo@atlas.edu', 'Silva', 'Julieta', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_ling', crypt('pass123', gen_salt('bf', 10)), 'doc_ling@atlas.edu', 'Romero', 'Nicolas', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_arq', crypt('pass123', gen_salt('bf', 10)), 'doc_arq@atlas.edu', 'Sosa', 'Victoria', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_cs_edu', crypt('pass123', gen_salt('bf', 10)), 'doc_cs_edu@atlas.edu', 'Suarez', 'Facundo', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_ed_exp', crypt('pass123', gen_salt('bf', 10)), 'doc_ed_exp@atlas.edu', 'Alonso', 'Martina', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_hist_reg', crypt('pass123', gen_salt('bf', 10)), 'doc_hist_reg@atlas.edu', 'Blanco', 'Joaquin', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_lit', crypt('pass123', gen_salt('bf', 10)), 'doc_lit@atlas.edu', 'Dominguez', 'Paula', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente'));

-- 2. Insert Docentes details
INSERT INTO public.docentes (usuario_id, docente_dni, docente_cuil, docente_fecha_nac, docente_email_institucional, docente_fecha_ingreso, docente_domicilio, docente_antig_previa, docente_estado)
SELECT usuario_id, 10000000 + usuario_id, 20100000000 + usuario_id, '1980-01-01', usuario_correo, '2015-01-01', 'Calle Falsa 123', 0, 'Activo'
FROM public.usuarios WHERE usuario_username LIKE 'doc_%';

-- 3. Insert Designaciones (all Activo)
INSERT INTO public.designaciones (designacion_numero_resolucion, designacion_fecha_inicio, designacion_estado_actual, usuario_id)
SELECT 2000 + usuario_id, '2015-01-01', 'Activo', usuario_id
FROM public.usuarios WHERE usuario_username LIKE 'doc_%';

-- 4. Insert Cargos, linking each new docente designacion to one specific unit
-- We use a CTE or explicit inserts to link them exactly to the 20 units.
-- To be absolutely precise and ensure each unit has exactly one cargo in this batch, we will write 20 explicit cargo inserts.

INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(6001, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_orq') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Creación. Art. Orq.' LIMIT 1)),
(6002, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_tornambe') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Tornambé Centro de Creación' LIMIT 1)),
(6003, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_filo') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Filosofía y Ciencias de la Educación' LIMIT 1)),
(6004, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_geo') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Geografía' LIMIT 1)),
(6005, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_historia') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Historia' LIMIT 1)),
(6006, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_ingles') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Lengua y Literatura Inglesa' LIMIT 1)),
(6007, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_letras') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Letras' LIMIT 1)),
(6008, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_musica') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Música' LIMIT 1)),
(6009, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_turismo') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Turismo' LIMIT 1)),
(6010, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_icb') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Ciencias Básicas - ICB' LIMIT 1)),
(6011, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_geo_ap') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Geografía Aplicada' LIMIT 1)),
(6012, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_est_mus') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Estudios Musicales' LIMIT 1)),
(6013, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_exp_vis') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Experiencia Visual' LIMIT 1)),
(6014, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_inst_filo') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Filosofía' LIMIT 1)),
(6015, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_ling') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Investig. Lingüísticas y Filológicas' LIMIT 1)),
(6016, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_arq') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Investig. Aqueológicas y Museo' LIMIT 1)),
(6017, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_cs_edu') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Investig. en Ciencias de la Educación' LIMIT 1)),
(6018, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_ed_exp') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Investig. en Educación en Ciencias Experimentales' LIMIT 1)),
(6019, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_hist_reg') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Investig. en Historia Regional y Argentina' LIMIT 1)),
(6020, 10, '2015-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lit') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Litertura - Ricardo Güiraldes' LIMIT 1));

-- =========================================================================
-- ADDITIONAL MOCK DATA: LICENCIAS
-- =========================================================================

-- Insert Motivos Licencias
INSERT INTO public.motivos_licencias (motivo_l_id, motivo_l_nombre, motivo_l_dias_corresp) VALUES
(1, 'Maternidad', 90),
(2, 'Enfermedad', 30),
(3, 'Estudio', 15),
(4, 'Razones Particulares', 6);

-- 1. Insert Users for Licencia
INSERT INTO public.usuarios (usuario_username, usuario_contrasenia, usuario_correo, usuario_apellido, usuario_nombre, usuario_activo, rol_id) VALUES
('doc_lic1', crypt('pass123', gen_salt('bf', 10)), 'doc_lic1@atlas.edu', 'Gutierrez', 'Pablo', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente')),
('doc_lic2', crypt('pass123', gen_salt('bf', 10)), 'doc_lic2@atlas.edu', 'Herrera', 'Marta', true, (SELECT rol_id FROM public.roles WHERE rol_nombre = 'Docente'));

-- 2. Insert Docentes details (estado = 'Licencia')
INSERT INTO public.docentes (usuario_id, docente_dni, docente_cuil, docente_fecha_nac, docente_email_institucional, docente_fecha_ingreso, docente_domicilio, docente_antig_previa, docente_estado) VALUES
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic1'), 40111222, 20401112224, '1995-01-01', 'doc_lic1@atlas.edu', '2020-01-01', 'Calle L 1', 0, 'Licencia'),
((SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic2'), 40222333, 27402223335, '1996-02-02', 'doc_lic2@atlas.edu', '2021-02-02', 'Calle L 2', 0, 'Licencia');

-- 3. Insert Designaciones
INSERT INTO public.designaciones (designacion_numero_resolucion, designacion_fecha_inicio, designacion_estado_actual, usuario_id) VALUES
(3001, '2020-01-01', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic1')),
(3002, '2021-02-02', 'Activo', (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic2'));

-- 4. Insert Cargos
INSERT INTO public.cargos (cargo_codigo, cargo_horas_ocupadas, cargo_fecha_creacion, origen_id, caracter_id, categoria_id, dedicacion_id, designacion_id, unidad_id) VALUES
(7001, 10, '2020-01-01', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic1') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Matemática' LIMIT 1)),
(7002, 10, '2021-02-02', 1, 1, 1, 1, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic2') LIMIT 1), (SELECT unidad_id FROM public.unidades WHERE unidad_nombre = 'Historia' LIMIT 1));

-- 5. Insert Licencias for these new docentes
INSERT INTO public.licencias (licencia_nro_resolucion, licencia_fecha_inicio, licencia_fecha_fin, licencia_fecha_fin_estim, motivo_id, licencia_cantidad_dias, designacion_id) VALUES
('RES-2024-400', '2024-05-01', NULL, '2024-05-15', 2, 15, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic1') LIMIT 1)),
('RES-2024-500', '2024-06-10', NULL, '2024-09-10', 1, 90, (SELECT designacion_id FROM public.designaciones WHERE usuario_id = (SELECT usuario_id FROM public.usuarios WHERE usuario_username = 'doc_lic2') LIMIT 1));
