spring.application.name=atlas-backend

#Conexión a la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/ATLAS
spring.datasource.username=postgres
spring.datasource.password=8264
#spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración estricta de JPA para respetar tu diseño en pgAdmin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port = 8081