spring.application.name=atlas-backend

#Conexión a la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/ATLAS
spring.datasource.username=postgres
spring.datasource.password=8264
#spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración estricta de JPA para respetar tu diseño en pgAdmin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port = 8081

# Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:user}
spring.mail.password=${SPRING_MAIL_PASSWORD:pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false